let input = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`;

const grid = input
  .trim()
  .split("\n")
  .map((line) => line.trim().split(""));

let splits = 0;
for (let row = 1; row < grid.length; row++)
  for (let column = 0; column < grid[0].length; column++)
    if (
      grid[row][column] === "." &&
      (grid[row - 1][column] === "S" ||
        grid[row - 1][column] === "|" ||
        (grid[row - 1][column + 1] === "|" && grid[row][column + 1] === "^") ||
        (grid[row - 1][column - 1] === "|" && grid[row][column - 1] === "^"))
    )
      grid[row][column] = "|";
    else if (grid[row][column] === "^" && grid[row - 1][column] === "|")
      splits++;

console.log(grid.map((line) => line.join("")).join("\n"));
console.log(splits);
